// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // При next build DATABASE_URL может быть не задан; для db push/migrate подставьте в .env
    url: process.env["DATABASE_URL"] ?? "postgresql://localhost:5432/pulse",
  },
});
